# Generated by Django 4.2 on 2024-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gateway',
            field=models.CharField(choices=[('rocket', 'DBBL Rocket'), ('nagad', 'Nagad')], default='rokcet', max_length=100),
        ),
    ]
