# Generated by Django 4.2 on 2024-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0003_remove_registration_email_remove_registration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='reg_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
