# Generated by Django 4.2 on 2024-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0007_registration_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
