# Generated by Django 4.2 on 2024-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0009_registration_approved_at_registration_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
