# Generated by Django 4.2 on 2024-02-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0011_remove_groupmember_other_info_alter_groupmember_inst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
