# Generated by Django 4.2 on 2024-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0012_alter_registration_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gateway',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad')], default='rokcet', max_length=100),
        ),
    ]
