# Generated by Django 4.2 on 2024-02-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0013_alter_registration_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gateway',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paying_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
