# Generated by Django 4.2 on 2024-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0015_alter_registration_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='game_controller',
            field=models.CharField(blank=True, choices=[('keyb', 'Keyboard'), ('joys', 'Joystick')], max_length=5, null=True),
        ),
    ]
