# Generated by Django 4.2 on 2024-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0016_groupmember_game_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contest',
            field=models.CharField(choices=[('lfr', 'Line Follower Robot'), ('poster', 'Poster Presentation'), ('circuit-solve', 'Circuit Master'), ('integration', 'Integration Bee'), ('gaming-fifa', 'Gaming Contest FIFA'), ('gaming-chess', 'Gaming Contest Chess')], max_length=20),
        ),
    ]
